version: "3.1"

services:
  db:
    container_name: "node-pokemon-db"
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}

  adminer:
    container_name: "node-pokemon-admin"
    image: adminer
    restart: always
    ports:
      - ${ADMIN_PORT}:8080
    depends_on:
      - db
